### ISSUE TITLE
Creating onnxjs from master

### ISSUE THREAD

**Issue by astu9880** [Microsoft/onnxjs#100]
How do we create onnxjs from source since the file available on cdn is outdated?

**Comment by fs-eire** [comment]
You can always run `npm run build` in source root to create the artifacts. BTW the next release is soon, as #99 is on the way.

**Comment by SubhiH** [comment]
> npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! onnxjs@0.1.4 build: `tsc && node tools/build --build-wasm --build-bundle`
npm ERR! Exit status 1
npm ERR! Failed at the onnxjs@0.1.4 build script 'tsc && node tools/build --build-wasm --build-bundle'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the onnxjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && node tools/build --build-wasm --build-bundle
[npm-debug.log](https://github.com/Microsoft/onnxjs/files/2931574/npm-debug.log)

**Comment by SubhiH** [comment]
Now, it is available here: https://cdn.jsdelivr.net/npm/onnxjs/dist/onnx.min.js
Thanks! :)

**Comment by fs-eire** [comment]
@SubhiH For the error that you have encountered, it looks like some error occurred inside tools/build.ts. there seems not enough logs for identifying the issue.

check the following dependencies if you want to pass the build by yourself in future:
- Node.js latest LTS (ie. 10.x)
- Python (2.7 or 3.6+)

**Comment by hariharans29** [comment]
Closing this issue as the original issue reported was CDN behind master. Now that is fixed.

If build issue is encountered again with the minimum required dependencies installed as listed above, please open another issue.
