### ISSUE TITLE
OutOfMemoryError with WASM back-end

### ISSUE THREAD

**Issue by SubhiH** [Microsoft/onnxjs#115]
After running the model tens of time with **wasm** back-end, I get a memory error.

**Comment by hariharans29** [comment]
Hello,

Thanks for raising this issue. This is the first time we are seeing an OutOfMemoryError thus far. Can you please share more context ?

1) Platform/ System specs
2) Model
3) Code showing how the model is invoked

**Comment by SubhiH** [comment]
1. Platform:
    1. OS: Ubuntu.
    2. Browser: Chrome.
    3. Model: mxnet -> onnx -> onnxjs with wasm back-end.

2. Model: similar to MobileNet with a couple of more conv layers.

3. Code:

```
///called once to load the model
async function load(){
   await session.loadModel("model.onnx");
}

async function runModel(input_img) {
  var inputTensor = new onnx.Tensor(input_img.data, 'float32', [1, 3, width, height]);
  var res = await session.run([inputTensor]);
  setTimeout(function(){runModel(input_img);}, 0);
}
```

I have noticed from the monitor that the memory usage is increasing rapidly (tens of MBs).

Thank you!

**Comment by SubhiH** [comment]
I am sorry for the mess. I am using OpenCVJS to prepare the image for the model. It seems the problem is from OpenCVJS not ONNXJS although I am releasing all the resources. I am doing few test cases to check the source of memory error and confirm here to close the issue.
Thank you! :)

**Comment by hariharans29** [comment]
Thank you for confirming this. I have been trying to profile memory usage and it seems fairly constant to me. You can try our demo site here - https://microsoft.github.io/onnxjs-demo (and use the WASM backend), the memory usage is fairly constant over multiple runs (I don't notice any leak like situation). 
Please close this issue after your tests confirm the source of memory error.

**Comment by SubhiH** [comment]
So sorry for wasting your time. I confirm that the memory issue is not related to ONNXJS.
