### ISSUE TITLE
TypeError: unrecognized operator 'Upsample'

### ISSUE THREAD

**Issue by christophstach** [microsoft/onnxjs#117]
When using a style transfer model compiled to onnx, I get the following Error in onnxjs 0.1.5:

**core.js:15724 ERROR Error: Uncaught (in promise): TypeError: unrecognized operator 'Upsample'
TypeError: unrecognized operator 'Upsample'**

I am using the pytorch function 

```python
x = F.interpolate(x, mode='nearest', scale_factor=self.scale_factor)
```

which is translated to the onnx Upsample operator, wich is not supported in onnxjs yet.

**Comment by gnsmrky** [comment]
@christophstach You will have to implement Upsample() by Concat() ops. Here is a working [ONNX.js Fast Neural Style](https://gnsmrky.github.io/pytorch-fast-neural-style-onnxjs/). Still buggy but should work ok on desktop browsers.

I am still working on putting up the modified PyTorch code to GitHub. Should be done soon.

**Comment by fs-eire** [comment]
Thanks to @gnsmrky for the explaination. According to latest [ONNX spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Upsample), `Unsample` is deprecated in opset v10. Is there an equivalent alternative operators does the same thing?

**Comment by gnsmrky** [comment]
@fs-eire I believe the equivalent op would be [Resize](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize).  Still need PyTorch ONNX export to change accordingly, though.

**Comment by gnsmrky** [comment]
@christophstach Take a look at my [PyTorch fast-neural-style (FNS) for Web](https://github.com/gnsmrky/pytorch-fast-neural-style-for-web).  I've put up all the details to make the PyTorch FNS work with ONNX.js.  Some network model tweaking methods for running in browsers are mentioned.  Should give you a good reference to make it run with ONNX.js.

More technical details for op replacements are at [Making the PyTorch fast-neural-style (FNS) to ONNX.js conversion work in browsers](https://github.com/gnsmrky/pytorch-fast-neural-style-for-web/tree/master/docs).  It talks about how to make the network compatible with ONNX.js by modifying the PyTorch codes.

Hope this helps you and everyone here to know how PyTorch --> ONNX.js works better.

:)
