### ISSUE TITLE
Texture memory leak

### ISSUE THREAD

**Issue by ShuangLiu1992** [microsoft/onnxjs#119]
when running the demo from https://microsoft.github.io/onnxjs-demo/#/yolo or my own code that repeatedly calls run() on an onnx.InferenceSession() instance, the gpu memory goes to 99% quite often and the fps drops significantly, is there a way to manually free the allocated gpu memory?

**Comment by fs-eire** [comment]
The yolo model does occupy quite a mount of GPU memory, but it should be able to reuse the allocated memory for later runs. If you see GPU memory usage grows every time run() is called, that should be an unexpected leak.

There is a `dispose()` for session object, but currently this function is not yet exposed as a part of API.

For one inference session, a model does occupy quite a mount of GPU memory for the first time (warm up), but it should be able to reuse the allocated memory for later runs. If you see GPU memory usage grows every time run() is called, that should be an unexpected leak.

Do you see the GPU memory usage continue to increase per run() and goes 99% , or it goes to 99% immediately? What if you try using the UPLOAD IMAGE? And what if you stop the camera after 99%, does it drop or not

**Comment by ShuangLiu1992** [comment]
it shoots up to 99% and there is WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
also I forgot to mention there is another webgl context being used to render stuff, which does not have the same element id used by the ONNXJS context factory.

as of UPLOAD IMAGE, I couldn't repeat enough times to observe any gpu memory leakage

**Comment by fs-eire** [comment]
I did some test and verified that there are texture leak, at least for some operators. Will work on it to find out the root cause.

**Comment by fs-eire** [comment]
PR #139 should be able to fix this issue.

**Comment by fs-eire** [comment]
Fixed in ONNX.js v0.1.6. Please retry the onnxjs demo.

**Comment by fs-eire** [comment]
> Fixed in ONNX.js v0.1.6. Please retry the onnxjs demo.

this is my bad. the PR #139 is not yet merged and it is not included in v0.1.6. re-open this issue. sorry for the confusing

**Comment by ShuangLiu1992** [comment]
fixed in #139
