### ISSUE TITLE
webgl extension

### ISSUE THREAD

**Issue by ShuangLiu1992** [microsoft/onnxjs#145]
with the latest release I'm getting this error with chrome on android. (samsung note 9, samsung s6)

[.WebGL-0xcc479c00]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: GL_BLEND with floating-point color attachments requires the EXT_float_blend extension

**Comment by ShuangLiu1992** [comment]
is there anyway to force webgl1 context since this extension doesn't seem to be supported on android?

**Comment by ShuangLiu1992** [comment]
I can switch the context to webgl1 with 
` onnx.backend.webgl.contextId = 'webgl';`

then it gives me 
```
GlContextFactory 2019-05-07T14:33:10.547Z|failed to create WebGLContext using contextId 'webgl' or 'experimental-webgl'. Error: Error: both float32 and float16 TextureType are not supported
:8000/onnx.js:1 [30;43mw WebGLBackend 2019-05-07T14:33:10.549Z|Unable to initialize WebGLBackend. Error: WebGL is not supported
```

**Comment by fs-eire** [comment]
It looks like GL_BLEND not working on Samsung devices (it works on Google Pixel, LG, Sony, OnePlus and so on. I don't have any Huawei, Xiaomi so not sure about those)

What makes the situation worse is, the WebGL extension availability is not detectable. The [spec](https://www.khronos.org/registry/webgl/extensions/EXT_float_blend/) indicates that `EXT_color_buffer_float` should enable BLEND in "supported systems". Samsung devices support this extension but it is apparently not among the "supported systems". This means there is no easy way to detect whether GL_BLEND is supported.

For WebGL1, it is literally no float support on those Samsung devices. In WebGL1, `OES_texture_float` is required to create float32 format texture, and if it is not available, fallback to `OES_texture_half_float` to use float16. If neither is available there is no way to use webgl backend in ONNX.js. On Samsung devices those 2 extensions are not available in webgl1.

**Comment by ShuangLiu1992** [comment]
yea, I thought onnxjs was using webgl1 on ios but seems like it is just using wasm backend.
samsung phones are quite popular in eruope and tensorflowjs does support them (also supports synchronous inference).

onnxjs is a great framework and has lots of promises but at its current state we will have to go back to converting onnx models to keras then tensorflow js :c

**Comment by fs-eire** [comment]
On Samsung devices, WebGL2+no BLEND is the solution. I did a quick investigation on Samsung to disable BLEND and it passes the tests. I will work on this to fix the problem.

iOS webgl support is available in [v0.1.6](https://github.com/microsoft/onnxjs/releases/tag/v0.1.6)

**Comment by ShuangLiu1992** [comment]
also, it seems like grouped convolution where depth_multiplier is not 1 (out_channel != group || out_channel != in_channel) is not producing the correct results with webgl backend?

**Comment by ShuangLiu1992** [comment]
tried #149, can confirm this fixes a couple of issues on samsung devices

**Comment by Kirayue** [comment]
Hi, @ShuangLiu1992 
could you tell me how to build #149 code to onnx.min.js?
I clone the repo from fs-eire/onnx.js and checkout to android branch, and `npm i` but I got error for `Error: 404 status code downloading tarball https://github.com/fs-eire/onnxjs-node/releases/download/v0.3.0/onnxruntime-linux-x64-node-v57.tar.gz`

**Comment by fs-eire** [comment]
> Hi, @ShuangLiu1992
> could you tell me how to build #149 code to onnx.min.js?
> I clone the repo from fs-eire/onnx.js and checkout to android branch, and npm i but I got error for Error: 404 status code downloading tarball https://github.com/fs-eire/onnxjs-node/releases/download/v0.3.0/onnxruntime-linux-x64-node-v57.tar.gz

looks like you are using an older version than Node.js v8.11.2. Could you please try a newer Node.js version?

Node.js NAPI support table: https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix
