### ISSUE TITLE
But, There is no response when click the "run button" in my web page.

### ISSUE THREAD

**Issue by bemoregt** [microsoft/onnxjs#146]
Hi, @jdhuntington @chad @sverrejoh @bgianfo @radical 

I tried simple resnet50_8.onnx model with default cat image.

But, There is no response when click the "run button" in my web page.

What's wrong to me?

My browsers are firefox & safari. Both browser's results are same. 

Thanks in advance.

**Comment by fs-eire** [comment]
Hi @bemoregt could you please share more information:
  - are you trying the [ONNX.js demo](https://microsoft.github.io/onnxjs-demo/) or you are building your own web app
    - if you are building your own webapp, which version of ONNX.js are you using
  - what is the device that you use

**Comment by bemoregt** [comment]
Hi, @fs-eire 

Further information here :

- I'm trying your ONNX.js demo.
-- How can I check my onnx.js version?
 
- What is the device that you use:
-- MacOSX Mojave x64, i7,  
-- node v12.1.0, npm 6.9.0 
-- Firefox 66.0.4
-- Safari 12.0.3

Thanks .

**Comment by fs-eire** [comment]
> Hi, @fs-eire
> Further information here :
> 
> 
> I'm trying your ONNX.js demo.
> -- How can I check my onnx.js version?
> 
> 
> What is the device that you use:
> -- MacOSX Mojave x64, i7,
> -- node v12.1.0, npm 6.9.0
> -- Firefox 66.0.4
> -- Safari 12.0.3
> 
> 
> Thanks .

I tried ONNX.js demo on both Safari 12 and Firefox 66 on macOS Mojave, and both works.

And you memtioned the "run button", this is strange. There is no such a button in the resnet50 demo. There are a dropbox with a prepared image list and a "upload image" button. Once either changed its content the model will run with the loaded image. Are you visiting https://microsoft.github.io/onnxjs-demo/ or another webpage?

**Comment by bemoregt** [comment]
Hi, @fs-eire @jdhuntington @chad @sverrejoh 

There is a button in this github demo source.

  <h1>Resnet50 Example</h1>
  <img id="imageSource" src="./resnet-cat.jpg"/>
  <div>
    <input type="button" value="Run" onclick="runExample()">
  </div>
<div id="predictions">

at https://github.com/microsoft/onnxjs/blob/master/examples/browser/resnet50/index.html

**Comment by bemoregt** [comment]
@fs-eire 

I followed this instruction.

https://github.com/microsoft/onnxjs/tree/master/examples/browser/resnet50

**Comment by fs-eire** [comment]
It looks like the instruction is not working... Change the steps in the instructions as described below:
 - use `http-server .. -c-1 -p 3000` instead of `http-server . -c-1 -p 3000`
 - then visit `http://localhost:3000/resnet50/` instead of `http://localhost:3000`

The problem is because some shared js files (under `../common/`) are failed to serve
