### ISSUE TITLE
Error: load converted models keras2onnx

### ISSUE THREAD

**Issue by opkm** [microsoft/onnxjs#147]
Error: invalid name for initializer: W when load model
this first conv layer in model

**Comment by fs-eire** [comment]
This looks like the graph has an initializer named `W`, but it's not in the model's input list. Initializers should always be applied to graph's inputs. could you check if:
  - tensor `W` is not used in the graph
  - it is `w` instead of `W` (tensor names are case-sensitive)

**Comment by opkm** [comment]
graph.initializer have all nodes, but graph.input only one node
![5468387](https://user-images.githubusercontent.com/42702201/57511910-c48aef80-7323-11e9-811b-e2f7ffe4beba.png)

**Comment by opkm** [comment]
model 
[wpod.zip](https://github.com/microsoft/onnxjs/files/3165718/wpod.zip)
