### ISSUE TITLE
Uncaught (in promise) TypeError: cannot resolve operator 'BatchNormalization' with opsets: ai.onnx v6 

### ISSUE THREAD

**Issue by beccaroskill** [microsoft/onnxjs#166]
#### Uncaught (in promise) TypeError: cannot resolve operator 'BatchNormalization' with opsets: ai.onnx v6
    at Object.e.resolveOperator (onnx.min.js:3744)
    at t.resolve (onnx.min.js:6679)
    at e.initializeOps (onnx.min.js:16130)
    at onnx.min.js:16046
    at t.event (onnx.min.js:1283)
    at e.initialize (onnx.min.js:16044)
    at e.<anonymous> (onnx.min.js:16021)
    at onnx.min.js:15953
    at Object.next (onnx.min.js:15966)
    at a (onnx.min.js:15854)

I suspect that this has to do with BatchNormalization only being supported in opsets v7+ (the error indicates that the package is utilizing opset v6). However, per documentation it seems that version 0.1.7 of this package utilizes opset v7. I'm using a webgl backend in browser (Chrome).

**Comment by buptWebAR** [comment]
Hi, I am facing with the same problem. Could you please provide me with some helpful suggestions? Thanks!

**Comment by Yolantele** [comment]
has anyone found the solution?

**Comment by fs-eire** [comment]
Close as this issue is out-of-dated. Latest exporter and converters supports opset v7+.
