### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by nevenp** [microsoft/onnxjs#170]
When is the next release of onnx.js scheduled? I am interested in support for more operators (especially Upsample, Shape and Max operators).

**Comment by Rishav1** [comment]
Seems like the development has halted. Is there any other onnx library that supports more recent ONNX Opsets?

**Comment by SharanSMenon** [comment]
What happened here?

**Comment by fs-eire** [comment]
A new release will be launched shortly. Please see also for the state of the project at #186
