### ISSUE TITLE
Missing 'InstanceNormalization' operator

### ISSUE THREAD

**Issue by gnsmrky** [Microsoft/onnxjs#18]
Lately Instance Normalization (IN) has become popular.  Just curious if IN is being planned to be added?  Would love to see that for wasm backend. 

ONNX.js operator list:
https://github.com/Microsoft/onnxjs/blob/master/docs/operators.m

BTW, ONNX runtime does have IN supported:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#InstanceNormalization

**Comment by yhung119** [comment]
Hi, I would love to take on this issue. Is anyone else working on this already?

**Comment by hariharans29** [comment]
@gnsmrky and @JamesOscar - Thanks for your interest in ONNX.JS. #82 should have the IN operator for the `wasm` backend and the default `cpu` backend

@yhung119  - I have a simplistic implementation for this already. Please feel free to take a look to see if it can be improved. Additionally, the IN operator for the `webgl` backend can be tackled as well :). Thanks for your interest in contributing to ONNX.JS.

**Comment by gnsmrky** [comment]
@hariharans29 #82 has few errors. Is it still good to use it?  Or should wait until official stable release?

I actually worked around this issue by implementing InstanceNorm in PyTorch and managed to run it on ONNX.js now.

**Comment by hariharans29** [comment]
@gnsmrky 

Thanks for your comment. It's great to know that you have a work-around. Some comments/questions - 

1) You are more than welcome to wait for the next official release, but as far as I can see, #82 passes build and has passed all tests (including the IN op specific tests). The red crosses that you probably are referring to on the PR page pertains to the fact that it's still pending a review and hence it is not yet ready to merge. Barring a few minor changes relating to PR feedback, I probably expect it to be merged to master (and hence available in the next release). I have requested a review and I will await feedback.

2) In your comment, you mentioned that you were interested in the `wasm` backend. Is that still the case now ? #82 only supports the `wasm` backend and the default `cpu` backend for the IN op (just FYI).

**Comment by hariharans29** [comment]
Closing this as #82 is merged to master and primarily addresses the issue of missing IN op in ONNX.js. Currently, cpu and wasm backends are supporting IN op.
