### ISSUE TITLE
Convert image to tensors

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [microsoft/onnxjs#182]
Dear all,

I would like to ask how to convert an image to a tensor inside the frontend.

Thank you,

Cheers,

Francesco Saverio Zuppichini

**Comment by tngan** [comment]
@FrancescaLazzeri It maybe a late reply, you can use the image loader or create a canvas element yourself, but I am trying to do that in Node.js backend right now.

See the implementation [here](https://github.com/microsoft/onnxjs/blob/master/examples/browser/common/image-loader.js).

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @tngan thank you! I also see that, if you are using PyTorch, you can now create a data preprocessing pipeline (with torchvision.transform) and export it to oonx!

**Comment by tngan** [comment]
@FrancescoSaverioZuppichini Yes, I have another application using PyTorch to do the export and inference. I do think we don't need torch to do the inference and torch has a rather larger size in bundle. Actually, the ONNX export script is also included in the YOLOv5 repository now.
