### ISSUE TITLE
Question on load image function in load image.py

### ISSUE THREAD

**Issue by JonathanSum** [microsoft/onnxjs#238]
loadImageCb(url, cb) {
    loadImage(
      url,
      img => {
        if (img.type === 'error') {
          throw `Could not load image: ${url}`;
        } else {
          // load image data onto input canvas
          this.ctx.drawImage(img, 0, 0)
          //console.log(`image was loaded`);
          window.setTimeout(() => { cb(); }, 0);
        }
      },

Where is the loadImage come from?

**Comment by 28Smiles** [comment]
Its provided by `ndarray`
