### ISSUE TITLE
How to fetch emscripten built onnxruntime.a

### ISSUE THREAD

**Issue by dhirajnitk** [microsoft/onnxjs#247]
I am building c++ library that uses onnx runtime as library
Do we have any script to build emscripten  for onnx runtime. I built this codebase from source. It created wasm/js  files but I cant link them to c++ library as It would need  onnxruntime.a.

@hariharans29

**Comment by hariharans29** [comment]
This project is quite different from onnxruntime.
Answered your question here - https://github.com/microsoft/onnxruntime/issues/6160#issuecomment-747911107

**Comment by dhirajnitk** [comment]
Any help on building emscripten for onnxruntime will be deeply appreciated.
