### ISSUE TITLE
ResNet50 Example with 94mb resnet50.onnx times out on Chrome with "Page Unresponsive"

### ISSUE THREAD

**Issue by samjgorman** [microsoft/onnxjs#311]
Appears that the large size of ResNet50_8.onnx (94mb) triggers a "Page Unresponsive" consistently when replicated locally on Chrome 92.0. What size models can onnxjs reliably serve on Chrome?

Edit: I quit Chrome, restarted and was able to successfully run the ResNet example. This may be a local issue, but will leave this issue open in case others have experienced other performance issues on Chrome.

**Comment by fs-eire** [comment]
Thanks for your feedback.

Large models consumes a lot of resources in browsers ( and also GPU resources if webgl backend ), which makes it unstable. For web scenario, usually 10MB~20MB is stable enough in my experience.

-----
we are working on migrating ONNX.js to ONNX Runtime Web which offers enhanced user experience and improved performance. Please visit [ONNX Runtime Web](https://github.com/microsoft/onnxruntime/tree/master/js/web) to get more details.
