### ISSUE TITLE
Formator for pre-commit (PR Help)

### ISSUE THREAD

**Issue by joey00072** [microsoft/onnxjs#315]
I am tring to ass selu operator
```
test/data/ops/xor.jsonc 6ms
test/test-suite-whitelist.jsonc 21ms
ERR! pre-commit File(s) not formatted:
ERR! pre-commit lib/backends/cpu/ops/unary-op.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

I am getting this error wihile running npm `npm run pre-commit` with I have already used default vscode code formater,
which code formater should I use.

**Comment by fs-eire** [comment]
Hi @joey00072, you need the clang-format to format your ts code. Instructions are [here](https://github.com/microsoft/onnxjs/blob/master/docs/development.md).

----
Currently we are working on migrating ONNX.js to ONNX Runtime Web which offers enhanced user experience and improved performance. Please visit [ONNX Runtime Web](https://github.com/microsoft/onnxruntime/tree/master/js/web) to get more details.
