### ISSUE TITLE
npm install fails in the benchmark folder

### ISSUE THREAD

**Issue by miaobin** [Microsoft/onnxjs#48]
Dev environment is windows10, node.js v10.13.0, npm 6.4.1

The error messages are:
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.

**Comment by fs-eire** [comment]
Thanks for the feedback. It looks like package `circular-json@0.5.9` is an indirect dependency of `karma@3.1.1`. (`karma@3.1.1`->`log4js@3.0.6`->`circular-json@0.5.9`).

We will update package version in next package release to resolve this problem. Before that, you are OK to use the existing npm install with a deprecation warning (this does not fail the npm install).
