### ISSUE TITLE
Concat Bug

### ISSUE THREAD

**Issue by NTT123** [Microsoft/onnxjs#52]
https://github.com/Microsoft/onnxjs/blob/6ccc22568f7b9e712cf4bb803cf4b201f6314d3b/lib/backends/cpu/ops/concat.ts#L44

This line should be `else if (inputShape[axisIndex] !== dataNShape[axisIndex]) {`

Currently, it throws an exception when we concatenate two tensors of sizes (1, 2, 3, 4) and (1, 8, 3, 4) with axis=1.

**Comment by liuziyue** [comment]
Thank you for the feedback. It seems our test case didn't catch this scenario. We'll investigate and fix this issue.

**Comment by fs-eire** [comment]
This should have been fixed in #63
