### ISSUE TITLE
[Bug] Compute a node many times

### ISSUE THREAD

**Issue by NTT123** [Microsoft/onnxjs#53]
https://github.com/Microsoft/onnxjs/blob/c2f3de6d934e807ec7880ea3e9438ce519d1b8f6/lib/execution-plan.ts#L136

When a node has two identical inputs, e.g. `y = concat(x, x, dim=0)`, the above line will add `y` twice to the list `sequence`. This causes an exception at https://github.com/Microsoft/onnxjs/blob/c2f3de6d934e807ec7880ea3e9438ce519d1b8f6/lib/execution-plan.ts#L118  when y is computed the second time.

**Comment by hariharans29** [comment]
Fixed by #88
