### ISSUE TITLE
Unnatural node indexes

### ISSUE THREAD

**Issue by NTT123** [Microsoft/onnxjs#54]
https://github.com/Microsoft/onnxjs/blob/c2f3de6d934e807ec7880ea3e9438ce519d1b8f6/lib/graph.ts#L221-L233

These above lines add data buffer for the output nodes which is unnecessary because after that at 
https://github.com/Microsoft/onnxjs/blob/c2f3de6d934e807ec7880ea3e9438ce519d1b8f6/lib/graph.ts#L235-L271
these lines already take care of this task for all nodes in the graph.

Current implementation causes a confusion because the nodes have different indexes as compared to indexes in onnx graph. My suggestion is to put lines L221-L233 after scanning all the nodes to have natural indexes.

**Comment by fs-eire** [comment]
Do you mean to put the section `// scan all outputs` after `// scan all nodes`?

The code works after switching the 2 sections; but it does not help to preserve the indices of nodes in the original onnx graph: All model inputs will always be in front; a lot of processing may change it as well: removing `Constant`, `Identity` and `Dropout` ops, and graph optimizations may even fuse or split operators as well.

**Comment by NTT123** [comment]
OK. I will close this issue.
