### ISSUE TITLE
Uncaught (in promise) TypeError: unrecognized operator 'Squeeze'

### ISSUE THREAD

**Issue by ykim** [Microsoft/onnxjs#60]
After exporting a model from PyTorch to ONNX, I attempted to load the model using the code in the README and encountered this error:

```
Uncaught (in promise) TypeError: unrecognized operator 'Squeeze'
    at t.createOperator (session-handler.ts:180)
    at t.resolve (session-handler.ts:72)
    at e.initializeOps (session.ts:252)
    at session.ts:92
    at t.event (instrument.ts:294)
    at e.initialize (session.ts:81)
    at e.<anonymous> (session.ts:63)
    at inference-session-impl.ts:16
    at Object.next (inference-session-impl.ts:16)
    at a (inference-session-impl.ts:16)
```

I looked at the list of supported operators, and it looks like Squeeze isn't listed on it. Are there plans to support it?

**Comment by NTT123** [comment]
@ykim You can simply use `reshape` function as an alternative for squeeze.

Besides, you can checkout my squeeze (and unsqueeze) implementation for cpu and webgl backends at
https://github.com/NTT123/onnxjs

I've done it for my pytorch model recently.

**Comment by ykim** [comment]
@NTT123 Thanks for the suggestions. I'll take a look at your branch also.

**Comment by ykim** [comment]
@NTT123 Any chance you'll make a future PR for your squeeze and unsqueeze implementations?

**Comment by NTT123** [comment]
@ykim I've not submitted a PR for squeeze/unsqueeze because my current implementation is messy and redundant.

**Comment by fs-eire** [comment]
The latest release 0.1.3 supports `Squeeze`.
