### ISSUE TITLE
CDN file very far behind master

### ISSUE THREAD

**Issue by Jacques-L** [Microsoft/onnxjs#64]
When importing onnxjs via `<script src="https://cdn.jsdelivr.net/npm/onnxjs/dist/onnx.min.js"></script>`, the version of onnxjs obtained is very old, missing a couple of essential fixes. Is there any way get a newer version of onnxjs using `<script>`?

**Comment by fs-eire** [comment]
thanks for the feedback. we will release a new version and publish to npm in this week.

**Comment by fs-eire** [comment]
v0.1.2 is released today. I am planning to make a bi-weekly regular release, or an immediate release if any severe bugfix is on.
