### ISSUE TITLE
TypeError: unrecognized operator 'Flatten'

### ISSUE THREAD

**Issue by astu9880** [Microsoft/onnxjs#87]
I was able to bypass issue #84 by removing the functino x.size(). However, onnxjs doesn't support another operator I have use of i.e. Flatten. Is there a workaround for the same?

**Comment by astu9880** [comment]
@NTT123 @hariharans29

**Comment by NTT123** [comment]
In pytorch, we can use `view` function as an alternative for `flatten` function . However, 
here is the source code of torch.onnx exporting function for view ops:
https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L440
so, `x = x.view( *sizes) `, can be exported to either `Flatten ops` or `Reshape ops`.

Here we have three options:

  1. modify the above symbolic `view` function to export `reshape` ops only.
  2. use `x = x.view(*size)` cleverly so it falls into the case of exporting `reshape` ops.
  3. implement a `flatten` ops for ONNX.js

**Comment by fs-eire** [comment]
My understanding is, operator `Flatten` only changes the dims of the input tensor like `Reshape`, `Squeeze` and `Unsqueeze` do. If it is this case, it should be easy to implement this operator.

**Comment by astu9880** [comment]
@NTT123 I am unsure about how onnx C functions are working. Can you explain how the 1st and 2nd methods of your suggestion can be executed?

**Comment by alxmamaev** [comment]
Flatten also is using in [ResNet50 version 1](https://github.com/onnx/models/tree/master/models/image_classification/resnet) in ONNX Model Zoo,  so this model is not working in onnx.js

**Comment by NTT123** [comment]
As @fs-eire said, `Flatten` only changes the shape of input tensor. It should be very similar to my previous PR for `Squeeze` here https://github.com/Microsoft/onnxjs/pull/73/files . The only different is to use a new function `squeezeShape` instead of `flattenShape`.

@astu9880 1st and 2nd methods are basically implementing `flatten` function using reshape ops.

**Comment by fs-eire** [comment]
This should have been resolved in #93.
