### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by luiscastro193** [Microsoft/onnxjs#90]
I know you are aware of this issue but you can't realistically use this library in production until this is solved.

Awesome library, by the way :)

**Comment by gnsmrky** [comment]
Just curious, any progress in iOS support?  Just tried 0.1.4 on Safari, still does not work.

**Comment by fs-eire** [comment]
The current webgl backend does not work because rendering to float texture seems not supported so far on iOS. I will check if using half float works or not.

**Comment by fs-eire** [comment]
iOS support will be available in v0.1.6. release will happen in few days. see #132 #141

**Comment by fs-eire** [comment]
Fix available in ONNX.js v0.1.6
