### ISSUE TITLE
Clip operation is not supported

### ISSUE THREAD

**Issue by alxmamaev** [Microsoft/onnxjs#92]
If you trying to export and load MobilenetV2 (like in this [implementation](https://github.com/tonylins/pytorch-mobilenet-v2/blob/master/MobileNetV2.py))
You will get error: `unrecognized operator 'Clip'`
This error is except because in MobilenetV2 are using [ReLU6](https://pytorch.org/docs/stable/nn.html#torch.nn.ReLU6) instead ReLU.

**Comment by NTT123** [comment]
Instead of waiting for `clip` operation being supported, you can replace `ReLU6` module by the following custom module

```python
class MyReLU6(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        return  6 - nn.functional.relu( 6 - nn.functional.relu(x) ) 
```
